version: '3'

services:
  scheduler:
    build:
      context: ../schedulerService
      dockerfile: Dockerfile
    env_file:
      - ./scheduler.env
    links:
      - rabbitmq
      - slackservice
      - mailservice
    ports:
      - "1337:1337"

  slackservice:
    build:
      context: ../slackService
      dockerfile: Dockerfile
        env_file:
      - ./slackservice.env
    links:
      - rabbitmq
    ports:
      - "8080:8080"

  mailservice:
    build:
      context: ../emailService
      dockerfile: Dockerfile
    env_file:
      - ./mailservice.env
    links:
      - rabbitmq
    ports:
      - "8090:8090"

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"